# myApp/docker-compose.yaml
version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5001:5001'
    stdin_open: true
    tty: true